myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"

urlpatterns = [
    path('trail/',views.trial,name="Trial"),
    path('profile/',views.profile,name="profile"),
]

p6/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
     path('base/',views.base,name="base"),
    path('',views.home,name="home"),
    path('myapp/',include("myapp.urls")),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def trial(request):
    return HttpResponse("<h1>Project is on air</h1>")

def base(request):
    return render(request,"base.html")

def home(request):
    return render(request,"myapp/home.html")

def profile(request):
    name="akshay"
    return render(request,"myapp/profile.html",{'name':name})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>BASE Page</title>
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>
<body>
 {% include "partials/_topbar.html" %}
 {% include "partials/_navbar.html" %}

    
    {% block content %}
      <div class="container">
        <div class="jumbotron">
            <h1>Welcome to base page</h1>
        </div>
      </div>
    {% endblock %}
    {% include "partials/_footer.html" %}
</body>
</html>

templates/myapp/home.html
{% extends "base.html" %}

{% block title %}
    <title>Home Page</title>
{% endblock %}

{% block content %}
      <div class="container">
        <div class="jumbotron">
            <h1>Welcome to Home page</h1>
        </div>
      </div>
{% endblock %}

templates/myapp/profile.html
{% extends "base.html" %}

{% block title %}
    <title>Profile Page</title>
{% endblock %}

{% block content %}
      <div class="container">
        <div class="jumbotron">
            <h1>Welcome to {{name}} Profile page</h1>
        </div>
      </div>
{% endblock %}

templates/partials/_footer.html
<div class="alert alert-primary" role="alert">
    <center>Footer</center> 
  </div>

templates/partials/_navbar.html
<!--nav bar-->
<div class="container">
    <ul class="nav">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'myapp:profile' %}">Profile</a>
        </li>
        
      </ul>
</div>

templates/partials/_topbar.html
<div class="alert alert-secondary" role="alert">
    <center>Top Bar</center> 
 </div>